server:
  port: 8080  # ???

spring:
  datasource:
    url: ${DB_URL}           # ????
    username: ${DB_USERNAME} # ????
    password: ${DB_PASSWORD} # ????
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update       # ???
    properties:
      hibernate:
        format_sql: true     # ???
        show_sql: false      # ???

  redis:
    host: ${REDIS_HOST}      # ????
    port: ${REDIS_PORT}      # ????
    password: ${REDIS_PASSWORD:}  # ??? ENV, ??? ? ?

jwt:
  secret: ${JWT_SECRET}      # ????
  access-expiration: 3600000     # 1?? (???)
  refresh-expiration: 604800000  # 7?   (???)

youtube:
  api-key: ${YOUTUBE_API_KEY}     # ????

logging:
  level:
    org.hibernate.SQL: INFO       # ???
